### ISSUE TITLE
View control mouse interaction issues

### ISSUE THREAD

**Issue by iche033** [gazebosim/gz-gui#293]
## Environment
* OS Version: Ubuntu 18.04
* Source or binary build?
 both binary and source, ignition fortress pre2
  
## Description

I ran into a few gui view control interaction issues with the mouse.  I don't see these issues using the old GzScene3D plugin. 

I can separate them into different issues if needed.

1. Incorrect mouse anchor point. 
  * This doesn't happen all the time but it happens often enough that it's quite easily reproducible on my machine. I also see incorrect anchor points for panning the camera from time to time, e.g. camera jumps when panning after resizing the render window or unexpected large camera pan movement because anchor point used is closer than actual point.

![gui_view_anchor](https://user-images.githubusercontent.com/4000684/134997095-8dd84ebf-2df7-41b8-8f0c-329f41781729.gif)

2. Context menu triggered on mouse release after a zoom action
  * Looks like the menu is triggered on all right mouse button releases. We should not open the context menu after a mouse right button drag.
 
![gui_view_context](https://user-images.githubusercontent.com/4000684/134997858-8069aa66-3237-4c7f-8ddd-4060b755e5ab.gif)

3. Scroll zoom moves camera in wrong direction
  * The first zoom with scroll button works as expected. However, if you try to zoom again in the opposite direction, the **first scroll increment** will be in the wrong direction (still in the previous direction) correct.

![gui_view_zoom](https://user-images.githubusercontent.com/4000684/134997607-2ff50317-da02-4c6a-95eb-e7fd959526e0.gif)

**Comment by chapulina** [comment]
Fixes on #295
