### ISSUE TITLE
[Scene3D] Memory leak on resize

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-gui#35]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/35)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
When resizing the scene 3D plugin, I can see using `top` that the memory almost doubles each time the window is resized.

I traced it down to [these](https://github.com/ignitionrobotics/ign-gui/blob/bfb84a8797a0ad34c22892d8dc8019c188021d35/src/plugins/Scene3D.cc#L461) lines on `Scene3D`. If I comment out `SetImageWidth`, `SetImageHeight` and `SetAspectRatio`, the issue doesn't happen.

The comment on the code, `setting the size should cause the render texture to be rebuilt` led me to [OgreRenderTarget::RebuildImpl](https://github.com/ignitionrobotics/ign-rendering/blob/400f1d31f3c0b40f6fa6426249bf93df5a1b95a3/ogre/src/OgreRenderTarget.cc#L136). There are some "destroy" functions which are not implemented there.

I started trying to implement them [here](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-rendering/commits/2ddaf44076439445cda7c565a564a26cd6bacb07) (ignitionrobotics/ign-rendering@1af343b85b9f5e4d01faeca095a9b1b95d223e4c), but the memory leak is still happening.

@iche033 , any tips?

**Comment by iche033** [comment]
found a [related post](https://forums.ogre3d.org/viewtopic.php?p=548396#p548396) in ogre forum about depth buffer textures not being cleaned up in ogre 2.x

**Comment by jennuine** [comment]
Since we've been using `MinimalScene` and `Scene3D` is deprecated, closing this issue.
