### ISSUE TITLE
Some plugins not properly loaded in debug mode

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/gz-gui#41]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/issues/41)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Description 

[Description of the issue]

# Steps to Reproduce

1. Compile in debug mode
1. Run the `UNIT_WorldStats_TEST`

**Expected behavior:**  

Test passes

**Actual behavior:**

Test fails to find the rendering plugin:

~~~
[Dbg] [Application.cc:87] Initializing application.
[GUI] [Dbg] [Application.cc:404] Create main window
[GUI] [Msg] Loading plugin [WorldStats]
 loaded plugins : 0
[GUI] [Err] [Application.cc:334] Failed to load plugin [WorldStats] : couldn't load library on path [/home/ian/depot/ign_ws/build/ign_gui/lib/libWorldStats.so].
/home/ian/depot/ign_ws/src/ign-gui/src/plugins/WorldStats_TEST.cc:43: Failure
Value of: app.LoadPlugin("WorldStats")
  Actual: false
Expected: true
~~~

**Reproduces how often:** 

:100: % of the time

# Versions

ign-gui1

# Additional Information

See discussion on [pull request #186](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-gui/pull-requests/186)

**Comment by jennuine** [comment]
I've tried this with `gz-gui8` and it is passing now. Closing since this appears stale.
