### ISSUE TITLE
Add "topic" parameter to the "Teleop" plugin

### ISSUE THREAD

**Issue by Myzhar** [gazebosim/gz-gui#483]
## Desired behavior

The Teleop GUI plugin does not accept any parameter. 
Setting the topic by SDF would be really useful.

## Alternatives considered

N/A

## Implementation suggestion

The idea is to have something like this:

```
<plugin filename="Teleop" name="robot_name Teleop">
  <ignition-gui>
     <property type="string" key="state">docked</property>					
  </ignition-gui>
  <topic>/robot_name/cmd_vel</topic>
</plugin>
```

## Additional context

N/A

**Comment by ahcorde** [comment]
Hi@Myzhar , 
Teleop already support this. Check this line https://github.com/gazebosim/gz-gui/blob/ign-gui6/src/plugins/teleop/Teleop.cc#L139-L141.
```xml
        <plugin filename="Teleop">
          <ignition-gui>
            <title>Teleop!</title>
           </ignition-gui>
          <topic>your topic name here</topic>
        </plugin>
```
