### ISSUE TITLE
[gz-gui8] Fails to build MinimalScene if gz-rendering8 is built without vulkan support

### ISSUE THREAD

**Issue by oysstu** [gazebosim/gz-gui#585]
The vulkan external device header is guarded by GZ_RENDERING_HAVE_VULKAN
https://github.com/gazebosim/gz-rendering/blob/22b2bbfbe06ac68558d77948d339fbc294876c85/include/gz/rendering/RenderEngineVulkanExternalDeviceStructs.hh#L27-L63

This is essentially only set for builds using OGRE2/ogre-next and vulkan support.
https://github.com/gazebosim/gz-rendering/blob/22b2bbfbe06ac68558d77948d339fbc294876c85/CMakeLists.txt#L134-L159

The build therefore fails for gz-rendering8 with only ogre 1.9 or non-vulkan ogre-next.

Edit: due to the following include https://github.com/gazebosim/gz-gui/blob/872222acfab2f2279de73b35a81fd72d8b1cc1ec/src/plugins/minimal_scene/MinimalScene.cc#L43

**Comment by jennuine** [comment]
@iche033 do you mind to take a look?
